# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xF9aE87E9ACE51aa16AED25Ca38F17D258aECb73f"
    chainName: worldchain
    collateralAddressOrDenom: "0x2cFc85d8E48F8EAB294be644d9E25C3030863003"
    connections:
      - token: ethereum|ethereum|0x651D024C2304a372fa770228A7E1F3D8415041e2
      - token: ethereum|optimism|0x84F47b7f56ccFc5EDC37Ceaed0F9228d9A0b666B
    decimals: 18
    name: Worldcoin
    standard: EvmHypCollateral
    symbol: WLD
  - addressOrDenom: "0x651D024C2304a372fa770228A7E1F3D8415041e2"
    chainName: ethereum
    collateralAddressOrDenom: "0x163f8C2467924be0ae7B5347228CABF260318753"
    connections:
      - token: ethereum|worldchain|0xF9aE87E9ACE51aa16AED25Ca38F17D258aECb73f
      - token: ethereum|optimism|0x84F47b7f56ccFc5EDC37Ceaed0F9228d9A0b666B
    decimals: 18
    name: Worldcoin
    standard: EvmHypCollateral
    symbol: WLD
  - addressOrDenom: "0x84F47b7f56ccFc5EDC37Ceaed0F9228d9A0b666B"
    chainName: optimism
    collateralAddressOrDenom: "0x2cFc85d8E48F8EAB294be644d9E25C3030863003"
    connections:
      - token: ethereum|worldchain|0xF9aE87E9ACE51aa16AED25Ca38F17D258aECb73f
      - token: ethereum|ethereum|0x651D024C2304a372fa770228A7E1F3D8415041e2
    decimals: 18
    name: Worldcoin
    standard: EvmHypCollateral
    symbol: WLD
